trigger:
- none

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '0da7ae55-f78b-410c-90fb-cef156b34a60'
  
  # Web app name
  webAppName: 'java-spring-boot'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
    - job: MavenPackageAndPublishArtifacts
      displayName: display:Maven Package and Publish Artifacts
      pool: $(vmImageName)

      steps:
      - task: Maven@3
        displayName: Maven package
        inputs:
          mavenPomFile: 'app/pom.xml'
        
      - task: CopyFiles@2
        displayName: 'Copy Files to artifact staging directory'
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          Contents: '**/target/*.?(war|jar)'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish pipeline artifacts'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
  
  - stage: Deploy
    displayName: Deploy stage
    dependsOn: Build
    condition: succeeded()
    jobs:
    - job: DeployLinuxWebApp
      displayName: Deploy Linux Web App
      environment: development
      pool: $(vmImageName)

      steps:
      - task: DownloadPipelineArtifact@2
        displayName: 'Download Pipeline Artifact'
        inputs:
          buildType: 'current'
          
      - task: AzureWebApp@1
        displayName: 'Azure Web App Deploy: gs-spring-boot'
        inputs:
          azureSubscription: 'Pay-As-You-Go(0da7ae55-f78b-410c-90fb-cef156b34a60)'
          appType:  webAppLinux
          appName: '$(webAppName)'
          package: '$(System.DefaultWorkingDirectory)/drop/**/target/*.?(war|jar)'

